/***************************************************************
AUTHOR     DATE         Reference     Description
Sravya S   27/09/2022   ESCJ-1926    Call DONT/EERS realtime when a new account is created or an existing account is updated.
***************************************************************/

public class AccountReqWrapper {
    public String name {get;set;}  
    public String phone {get;set;}
}