/**
 * @author  : IBM
 * @Description : This class will help to maintain Constants
 * @Date : 16/02/2022
 *  
 * 
****************************************************************** 
Author    *      UserStory   *    Date         *       Description  
          
**/
public class CDConstants {
    
    //example
    public static final Decimal SOME_STATIC_VALUE = 20;
    public static final String SFU = 'SFU';
    public static final String COTTAGE = 'Cottage';
    public static final String MIDRISELESSTHAN100 = 'Midrise<100';
    public static final String MIDRISE = 'Midrise';
    public static final String HIGHRISE = 'Highrise';
    public static final String FTTU = 'FTTU';
    public static final String FTTB = 'FTTB';
    public static final String FTTIDF = 'FTTIDF';
    public static final String RETAIL = 'Retail';
    public static final String CTL_ON = 'CTL_ON';
    public static final String BULK_STR = 'Bulk';
    public static final String BURIED = 'Buried';
    public static final String AERIAL = 'Aerial';
    public static final String LESSTHAN100 = '<100';
    public static final String HYPHEN = '-';
    
    public static final Decimal HUNDRED = 100;
    public static final Decimal TWOLAKH = 200000;
    public static final Decimal ONELAKH = 100000;
    public static final Decimal FIFTHYTHOUSAND = 50000;
    public static final Decimal FIVETHOUSAND = 5000;
    public static final Decimal THREETHOUSAND = 3000;
    public static final Decimal TWOHUNDRED = 200;
    public static final Decimal POINTEIGHT = 0.8;
    public static final Decimal ZERO = 0;
    public static final Decimal ONE = 1;
    public static final integer SIX = 6;
    public static final integer EIGHT = 8;
    public static final integer TWELVE = 12;
    public static final integer SIXTEEN = 16;
    public static final integer TWENTYFOUR = 24;
    public static final integer FOURTYEIGHT = 48;
    public static final integer SIXTY = 60;
    public static final integer SEVENTYTWO = 72;
    public static final integer SIXTYFOUR = 64;
    public static final integer NINTYSIX = 96;
    public static final integer ONEFOURTYFOUR = 144;
    public static final integer TWOONESIX = 216; 
    public static final integer TWOEIGHTYEIGHT = 288;
    public static final integer THREESIXZERO = 360;
    public static final Decimal SEVENTYTWOPOINTZERO = 72.00000;
    public static final Decimal SIXTYFOURPOINTZERO = 64.00000;
    public static final Decimal NINTYSIXPOINTZERO = 96.00000;
    public static final Decimal ONEFOURTYFOURPOINTZERO = 144.00000;
    public static final Decimal TWOONESIXPOINTZERO = 216.00000;
    public static final Decimal TWOEIGHTYEIGHTPOINTZERO = 288.00000;
    public static final Decimal THREESIXZEROPOINTZERO = 360.00000;
    public static final integer TWO = 2;
    public static final integer THIRTYTWO = 32;
    public static final Decimal THIRTYTWOPOINTZERO = 32.00000;
    public static final integer FOURHUNDREDANDTHIRTYTWO = 432;
    public static final Decimal FOURHUNDREDANDTHIRTYTWOPOINTZERO = 432.00000;
    public static final Decimal ONEPOINTZEROFIVE = 1.05;
    public static final Decimal POINTTHREE = 0.3;

    public static final String GREENFIELD = 'Greenfield';
    public static final String BROWNFIELD = 'Brownfield';
    public static final String BROWNFIELD_OVERBUILD = 'Brownfield Overbuild';
        
    public static final String CTL_PROV_RUGGED = 'CTL provide Ruggedized';
    public static final String CTL_INSTALL = 'CTL install';
    public static final String DEV_INSTALL = 'Dev install';
    public static final String CTL_PROV_MICRO = 'CTL provide Microduct';
    public static final String CTL_PROV_DUCT = 'CTL provide Duct';
    public static final String CTL_PROV_FIBER = 'CTL provide Fiber';
    public static final String INTEGRATED = 'Integrated';
    public static final String INDOOR = 'indoor';
    public static final String NO_DROP = 'No Drop';
    public static final String NOT_NEEDED = 'Not needed';
    public static final String CLAMIX_ADTRAN = 'Calix/Adtran';
    public static final String YES = 'Yes';
    public static final String Y = 'Y';
    public static final String NO = 'No';
    public static final String N = 'N';
    public static boolean isUpdate = false;

	//QFCJ-4469 SmartNID RG Cost    
    public static final String SMART_NID_BASE_RG_COST_MODEL = 'AXON Q9500WK';
}//end class CDConstants