public class ProspectorConstants {
    //public static final String USERNAME             	= 'SFCJAPP';
    public static final String USERNAME_DEV         	= 'SFJCAPP-dev';
    public static final String MAPSERVICENAME       	= 'Telecom';
    public static final String MAPSERVICEID         	= '4';
    public static final String WKID                 	= '4326';
    public static final String PROJECTNAME_DEV         	= 'CJTEST-dev';

    public static final String LABEL_USERNAME       	= 'username';
    public static final String LABEL_MAPSERVICENAME 	= 'mapServiceName';
    public static final String LABEL_MAPSERVICEID   	= 'mapServiceId';
    public static final String LABEL_PROJECTID       	= 'projectId';

    public static final String CREATE_PROJECT       	= 'CreateProject';
    public static final String ADD_DEMAND_POINTS    	= 'AddDemandPoints';
    public static final String SUBMIT_JOB	        	= 'SubmitJob';
    public static final String LIST_JOBS	        	= 'ListJobs';
    public static final String GET_ROUTES_BY_PROJECT	= 'GetRoutesByProject';
}