import { createElement } from 'lwc';
import Lmn_RequiredFieldsLWCContract from 'c/lmn_RequiredFieldsLWCContract';

describe('c-lmn-required-fields-lwc-contract', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lmn-required-fields-lwc-contract', {
            is: Lmn_RequiredFieldsLWCContract
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});